“publish test workflow dev”
UOA-FSAE/functionBox pull request #3
Opened 2022-08-06 05:25 UTC by Toby-Osborne

“publish test workflow dev”
In all seriousness, I think its working now.  Note, that it will only publish it if you update the version number.  I might be able to find a fix for this but I do not currently have one.  Perhaps it doesn't need fixing.

2022-08-07 08:39 UTC, Jack17432 requested changes
Just need to change one thing and then its all good :)

2022-08-07 08:39 UTC, Jack17432 commented on .github/workflows/python-test.yml
> +on: [push]
Can we have it also on pull request (just for the test workflow)

2022-08-12 03:09 UTC, Toby-Osborne commented
Added the on pull request trigger to the testing workflow only

2022-09-05 06:30 UTC, Jack17432 commented
Looks good :)

2022-09-05 06:31 UTC, merged